### ISSUE TITLE
xml配置失效 @XxlConf 失效

### ISSUE THREAD

**Issue by aooppo** [xuxueli/xxl-conf#30]
```
<bean id="ds" class="com.zaxxer.hikari.HikariConfig">
	<property name="username" value="$XxlConf{default.username}" />
</bean>
```

```
	@XxlConf("default.password")
	private String pwd;
```

以上两种都不可用，只有XxlConfClient.get 好使.

Caused by: java.lang.RuntimeException: Driver org.postgresql.Driver claims to not accept jdbcUrl, $XxlConf{ge-erp.jdbc.url}
	at com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:106)
	at com.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:332)
	at com.zaxxer.hikari.pool.PoolBase.<init>(PoolBase.java:107)

**Comment by HelloJavaWorld123** [comment]
这个是咋解决的？

**Comment by HelloJavaWorld123** [comment]
spring mvc 项目，我得项目在配置时，跟上面一样不起作用，只有在xml中使用XxlConfClient.get 好使
