### ISSUE TITLE
zookeeper session 过期问题如何解决

### ISSUE THREAD

**Issue by ewang35** [xuxueli/xxl-conf#78]
com.xxl.conf.core.exception.XxlConfException: org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /xxl-conf/prod/service-gateway.zuul.router
        at com.xxl.conf.core.util.XxlZkClient.getPathData(XxlZkClient.java:254)
        at com.xxl.conf.core.core.XxlConfZkConf.get(XxlConfZkConf.java:129)
        at com.xxl.conf.core.core.XxlConfLocalCacheConf.reloadAll(XxlConfLocalCacheConf.java:125)
        at com.xxl.conf.core.core.XxlConfLocalCacheConf$1.run(XxlConfLocalCacheConf.java:56)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /xxl-conf/prod/service-gateway.zuul.router
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:130)
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
        at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:1105)
        at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:1133)
        at com.xxl.conf.core.util.XxlZkClient.getPathData(XxlZkClient.java:242)
        ... 4 common frames omitted

**Comment by xuxueli** [comment]
你好，session过期将会自动重连，并且会主动对比同步重连期间的变动配置数据。

高版本已经移除了zookeper依赖，改为更轻量级、开销更小的实现方式，建议升级体验。

**Comment by baojiange** [comment]
升级为1.6.2版本也会出现此问题
