### ISSUE TITLE
XXLJOB每天下午 17:30 左右的时候 就会自动关闭线程 和服务 ,帮忙看下 是 数据库线程池的问题,版本是2.3

### ISSUE THREAD

**Issue by zlt114** [xuxueli/xxl-conf#98]
`10:44:13.414 logback [main] INFO  c.x.job.admin.XxlJobAdminApplication - No active profile set, falling back to default profiles: default
10:44:14.814 logback [main] INFO  o.s.b.w.e.tomcat.TomcatWebServer - Tomcat initialized with port(s): 8080 (http)
10:44:14.823 logback [main] INFO  o.a.coyote.http11.Http11NioProtocol - Initializing ProtocolHandler ["http-nio-8080"]
10:44:14.824 logback [main] INFO  o.a.catalina.core.StandardService - Starting service [Tomcat]
10:44:14.824 logback [main] INFO  o.a.catalina.core.StandardEngine - Starting Servlet engine: [Apache Tomcat/9.0.31]
10:44:14.874 logback [main] INFO  o.a.c.c.C.[.[.[/xxl-job-admin] - Initializing Spring embedded WebApplicationContext
10:44:14.874 logback [main] INFO  o.s.web.context.ContextLoader - Root WebApplicationContext: initialization completed in 1273 ms
10:44:15.497 logback [main] INFO  c.x.j.a.c.scheduler.XxlJobScheduler - >>>>>>>>> init xxl-job admin success.
10:44:15.517 logback [xxl-job, admin JobFailMonitorHelper] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
10:44:15.619 logback [main] INFO  o.s.s.c.ThreadPoolTaskExecutor - Initializing ExecutorService 'applicationTaskExecutor'
10:44:15.695 logback [main] INFO  o.s.b.a.w.s.WelcomePageHandlerMapping - Adding welcome page template: index
10:44:15.707 logback [xxl-job, admin JobFailMonitorHelper] INFO  com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - Driver does not support get/set network timeout for connections. (oracle.jdbc.driver.T4CConnection.getNetworkTimeout()I)
10:44:15.711 logback [xxl-job, admin JobFailMonitorHelper] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
10:44:15.948 logback [main] INFO  o.s.b.a.e.web.EndpointLinksResolver - Exposing 2 endpoint(s) beneath base path '/actuator'
10:44:15.981 logback [main] INFO  o.a.coyote.http11.Http11NioProtocol - Starting ProtocolHandler ["http-nio-8080"]
10:44:16.019 logback [main] INFO  o.a.c.c.C.[.[.[/xxl-job-admin] - Initializing Spring DispatcherServlet 'dispatcherServlet'
10:44:16.019 logback [main] INFO  o.s.web.servlet.DispatcherServlet - Initializing Servlet 'dispatcherServlet'
10:44:16.025 logback [main] INFO  o.s.web.servlet.DispatcherServlet - Completed initialization in 4 ms
10:44:16.027 logback [main] INFO  o.s.b.w.e.tomcat.TomcatWebServer - Tomcat started on port(s): 8080 (http) with context path '/xxl-job-admin'
10:44:16.030 logback [main] INFO  c.x.job.admin.XxlJobAdminApplication - Started XxlJobAdminApplication in 2.94 seconds (JVM running for 3.48)
10:44:20.000 logback [xxl-job, admin JobScheduleHelper#scheduleThread] INFO  c.x.j.a.c.thread.JobScheduleHelper - >>>>>>>>> init xxl-job admin scheduler success.
10:44:20.015 logback [xxl-job, admin JobScheduleHelper#scheduleThread] WARN  c.x.j.a.c.thread.JobScheduleHelper - >>>>>>>>>>> xxl-job, schedule misfire, jobId = 2
10:44:20.020 logback [xxl-job, admin JobScheduleHelper#scheduleThread] WARN  c.x.j.a.c.thread.JobScheduleHelper - >>>>>>>>>>> xxl-job, schedule misfire, jobId = 3
10:44:20.021 logback [xxl-job, admin JobScheduleHelper#scheduleThread] WARN  c.x.j.a.c.thread.JobScheduleHelper - >>>>>>>>>>> xxl-job, schedule misfire, jobId = 4
10:44:20.021 logback [xxl-job, admin JobScheduleHelper#scheduleThread] WARN  c.x.j.a.c.thread.JobScheduleHelper - >>>>>>>>>>> xxl-job, schedule misfire, jobId = 5
10:44:20.022 logback [xxl-job, admin JobScheduleHelper#scheduleThread] WARN  c.x.j.a.c.thread.JobScheduleHelper - >>>>>>>>>>> xxl-job, schedule misfire, jobId = 6
10:44:20.022 logback [xxl-job, admin JobScheduleHelper#scheduleThread] WARN  c.x.j.a.c.thread.JobScheduleHelper - >>>>>>>>>>> xxl-job, schedule misfire, jobId = 7
13:14:23.605 logback [http-nio-8080-exec-8] INFO  o.a.coyote.http11.Http11Processor - Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: Invalid character found in method name. HTTP method names must be tokens
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:416)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:260)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
17:43:15.808 logback [SpringContextShutdownHook] INFO  o.s.s.c.ThreadPoolTaskExecutor - Shutting down ExecutorService 'applicationTaskExecutor'
17:43:16.810 logback [xxl-job, admin JobScheduleHelper#scheduleThread] INFO  c.x.j.a.c.thread.JobScheduleHelper - >>>>>>>>>>> xxl-job, JobScheduleHelper#scheduleThread stop
17:43:17.000 logback [xxl-job, admin JobScheduleHelper#ringThread] INFO  c.x.j.a.c.thread.JobScheduleHelper - >>>>>>>>>>> xxl-job, JobScheduleHelper#ringThread stop
17:43:17.811 logback [SpringContextShutdownHook] INFO  c.x.j.a.c.thread.JobScheduleHelper - >>>>>>>>>>> xxl-job, JobScheduleHelper stop
17:43:17.812 logback [xxl-job, admin JobLogReportHelper] INFO  c.x.j.a.c.thread.JobLogReportHelper - >>>>>>>>>>> xxl-job, job log report thread stop
17:43:17.813 logback [xxl-job, admin JobLosedMonitorHelper] INFO  c.x.j.a.c.thread.JobCompleteHelper - >>>>>>>>>>> xxl-job, JobLosedMonitorHelper stop
17:43:17.813 logback [xxl-job, admin JobFailMonitorHelper] INFO  c.x.j.a.c.t.JobFailMonitorHelper - >>>>>>>>>>> xxl-job, job fail monitor thread stop
17:43:17.814 logback [xxl-job, admin JobRegistryMonitorHelper-registryMonitorThread] INFO  c.x.j.a.c.thread.JobRegistryHelper - >>>>>>>>>>> xxl-job, job registry monitor thread stop
17:43:17.815 logback [SpringContextShutdownHook] INFO  c.x.j.a.c.t.JobTriggerPoolHelper - >>>>>>>>> xxl-job trigger thread pool shutdown success.
17:43:17.817 logback [SpringContextShutdownHook] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
17:43:17.855 logback [SpringContextShutdownHook] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
`
![Uploading image.png…]()

**Comment by zlt114** [comment]
![微信图片_20241220143746](https://github.com/user-attachments/assets/2e647b56-a448-4d8d-9435-804b1ae0d926)

**Comment by xuxueli** [comment]
这是 xxl-conf，可以补全日志问题提到job项目下
